ARG BASE_IMAGE_VERSION=latest

FROM postgres:${BASE_IMAGE_VERSION}

ENV POSTGRES_RESTORE_TARGET_DB_HOST=""
ENV POSTGRES_RESTORE_TARGET_DB_PORT=""
ENV POSTGRES_RESTORE_TARGET_USER=""
ENV POSTGRES_RESTORE_TARGET_PASSWORD=""
ENV POSTGRES_RESTORE_TARGET_DB_NAME=""

ENV POSTGRES_RESTORE_AWS_ACCESS_KEY_ID=""
ENV POSTGRES_RESTORE_AWS_SECRET_ACCESS_KEY=""
ENV POSTGRES_RESTORE_AWS_DEFAULT_REGION=""
ENV POSTGRES_RESTORE_AWS_S3_BUCKET=""
ENV POSTGRES_RESTORE_AWS_S3_PATH=""

ENV POSTGRES_RESTORE_AWS_CLI_VERSION=""
ENV POSTGRES_RESTORE_S3_ENDPOINT=""
ENV POSTGRES_RESTORE_DUMPFILE=""

RUN apt-get update && apt-get install -y dos2unix gzip curl unzip && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN dos2unix /usr/local/bin/entrypoint.sh && chmod +x /usr/local/bin/entrypoint.sh

VOLUME [ "/restore" ]

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]